#goal definition
string   operation 	#the operation can be 'add', 'addvalues', 'predict', 'forecast', 'entropy', 'evaluate', 'detect', 'update', 'delete'
			#'add' adds a sequence of given (by ID) state measurements and the times these have been obtained to the state's model, if ID is given for the first time, a new state is created and added to the model
			#'addvalues' adds a sequence of given (by ID) value measurements and the times these have been obtained to the state's model, if ID is given for the first time, a new state is created and added to the model
			#'predict'  calculates a sequence of probabilities of the state ID for the given times (i.e. prediction of one state for multiple time instants)
			#'forecast'  calculates a sequence of probabilities of the states with given 'ids' for the given time (i.e. prediction of mutiple states for a single time instant)
			#'entropy'  calculates a sequence of entropies of the state ID for the given times - this is to support exploration
			#'evaluate' predicts the state for the given times, compares the prediction with ground truth and returns the prediction errors for model orders from 0 to the order specified. Meant to help to decide which order to use for the 'predict' action. 
			#'detect' detects anomalies by predicting the state for the given times, comparing with ground truth and flagging up discrepancies that were beyond a certain 'confidence' level 
			#'delete' removes the current state from the collection of states   
			#'update' is reserved, will be used int the future for recalculating the models

string  id	  	#specifies the ID of the state to be manipulated 
string[]  ids	  	#specifies the IDs of the states to be manipulated - explusively fot the 'forecast' action
uint32[]  times 	#the time instants for the 'predict', 'add', 'entropy' and 'evaluate' actions

#specific for the 'predict', 'evaluate' and 'detect' actions
int32    order 		#number of periodic processes to use for the purpose of prediction (0 means a static model, typical value is 2), maximal order used for evaluation of the 'evaluate' action

#specific for the 'forecast' actions
int32[]  orders	  	#same as previous one, but for all states in the **ids** 

#specific for the 'add' and 'evaluate' action
bool[]      states   	#sequence of states observed at the particular times - specific to the 'add' action 	(this is for backward compatibility)
float32[]   values   	#sequence of values observed at the particular times - specific to the 'addvalues' action, (I recommend to normalize the values so they fit 0-1)

#specific for the 'detect' 
float32   confidence   	#confidence level for the anomaly detection

---
#result definition
int32 success		#action result - positive value indicates success, negative indicates error
string message 		#detailed message
float32[] probabilities	#probabilities of the states calculated by the 'predict' action for the particular 'times', probability of a given observation for the 'detect' action
float32[] entropies	#entropies of the states calculated by the 'entropy' action for the particular 'times'
float32[] errors 	#prediction errors for the various model orders given by the 'evaluate' action
uint32[]  anomalyTimes 	#the time instants of detected anomalies 
uint32[]  anomalyValues	#the observed anomaous states 
---
#feedback
string status
