#goal definition
string action 	 	#the action can be either "build" or "predict" or "timeline"
string mapName  	#specifies the map name for the "build" action or edge name for "timeline" action 
int64 startTime 	#specifies the start of model training time for "build" action or starting time for "timeline" action
int64 endTime  		#specifies the end of model training time for "build" action or end time for "timeline" action
int64 predictionTime  	#specifies the the prediction time for "predict" action or time step for "timeline" action
int32 resultOrder 	#model order for traversability prediction (0 is a static model, "-1" is an adaptive model, recommended is 2)
int32 durationOrder  	#model order for traversability prediction (0 is a static model, "-1" is an adaptive model, recommended is 0) 
---
#result definition
bool success
string message 
string[] edgeName
float32[] probability
float32[] duration
---
#feedback
string status
